import '.././globals.css';
import Loader from '@/components/Loader';
import { ClerkLoaded, ClerkLoading, ClerkProvider } from '@clerk/nextjs';

import SessionWrapper from '@/components/SessionWrapper';
import CommentModal from '@/components/CommentModal';
import LeftSidebar from '@/components/LeftSidebar';
import RightSidebar from '@/components/RightSidebar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className='antialiased'>
        <ClerkProvider>
          <ClerkLoading>
            <Loader />
          </ClerkLoading>
          <ClerkLoaded>
            <SessionWrapper>
              <div className='flex justify-between max-w-6xl mx-auto'>
                <div className='hidden sm:inline border-r h-screen sticky top-0'>
                  <LeftSidebar />
                </div>

                <div className='w-2xl flex-1'>{children}</div>

                <div className='lg:flex-col p-3 h-screen border-l hidden lg:flex w-[24rem]'>
                  <RightSidebar />
                </div>
              </div>
              <CommentModal />
            </SessionWrapper>
          </ClerkLoaded>
        </ClerkProvider>
      </body>
    </html>
  );
}
