// app/layout.js
import '../globals.css';
import { ClerkProvider, ClerkLoaded, ClerkLoading } from '@clerk/nextjs';
import { RecoilRoot } from 'recoil';
import Loader from '@/components/Loader';
import LeftSidebar from '@/components/LeftSidebar';
import RightSidebar from '@/components/RightSidebar';
import CommentModal from '@/components/CommentModal';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ClerkProvider>
          <ClerkLoading>
            <Loader />
          </ClerkLoading>
          <ClerkLoaded>
            <RecoilRoot>
              <div className="flex justify-between max-w-6xl mx-auto">
                <div className="hidden sm:inline border-r h-screen sticky top-0">
                  <LeftSidebar />
                </div>
                <div className="w-2xl flex-1">{children}</div>
                <div className="lg:flex-col p-3 h-screen border-l hidden lg:flex w-[24rem]">
                  <RightSidebar />
                </div>
              </div>
              <CommentModal />
            </RecoilRoot>
          </ClerkLoaded>
        </ClerkProvider>
      </body>
    </html>
  );
}
