import '.././globals.css';
import Loader from '@/components/Loader';
import { ClerkLoaded, ClerkLoading, ClerkProvider } from '@clerk/nextjs';

import SessionWrapper from '@/components/SessionWrapper';
import CommentModal from '@/components/CommentModal';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};
export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body>
          <ClerkLoading>
            <Loader />
          </ClerkLoading>
          <ClerkLoaded>{children}</ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );  
}